_target_: guided_diffusion.audio_datasets.LibriTTSDataset
root: "/datasets/LibriTTS"
subsets: ["train-clean-100", "train-clean-360", "train-other-500"]
sampling_rate: 16000
cache_dir: "/media/8tsp/dataset/cache/LibriTTS/16k/"
min_len: 80_000