_target_: guided_diffusion.audio_datasets.LibriTTSDataset
root: "/media/8tsp/dataset/LibriTTS_R"
subsets: ["train-clean-100", "train-clean-360", "train-other-500"]
sampling_rate: 16000
cache_dir: "/media/8tsp/dataset/cache/LibriTTS_R/16k/"