defaults:
  - model: unet
  - diffusion: gaussian_diffusion
  - dataset: libritts
  - _self_

schedule_sampler: "loss-second-moment"
# schedule_sampler: "uniform"
output_dir: results
audio_dir: ???
use_ema: false
segment_size: null
sampling_rate: 16000
device: cuda

batch_size: 32
# max_len: 80000
max_len: 80000
deterministic: False
num_workers: 8
microbatch: -1 # -1 disables microbatches

lr: 0.0001
ema_rate: "0.9999"  # comma-separated list of EMA values
weight_decay: 0.
lr_anneal_steps: 0
log_interval: 100
save_interval: 10000
resume_checkpoint: ".experiments/libritts/model050000.pt" # ".experiments/v24/model100000.pt"
use_fp16: True
fp16_scale_growth: 0.001
input_pertub: 0 # 0.15
cond_drop_rate: 0.5
