defaults:
  - model: unet_v6
  - diffusion: gaussian_diffusion
  - dataset: compound-libritts
  - _self_

schedule_sampler: "loss-second-moment"
# schedule_sampler: "uniform"
output_dir: results
audio_dir: ???
use_ema: false
segment_size: null
sampling_rate: 16000
device: cuda

batch_size: 128
# max_len: 80000
max_len: 80_000 # 80000
deterministic: False
num_workers: 8
microbatch: -1 # -1 disables microbatches

data_std: 0.2

lr: 0.0004
ema_rate: "0.9999"  # comma-separated list of EMA values
weight_decay: 0.
lr_anneal_steps: 0
log_interval: 100
save_interval: 2000
resume_checkpoint: ""
use_fp16: True
fp16_scale_growth: 0.001
input_pertub: 0.
cond_drop_rate: 0.5
