_target_: guided_diffusion.script_util.create_gaussian_diffusion
learn_sigma: false
sigma_small: true
steps: 200
noise_schedule: linear
timestep_respacing: ''
use_kl: false
predict_xstart: False
rescale_timesteps: false
rescale_learned_sigmas: false
input_sigma_t: true
# schedule_sampler: uniform